### ISSUE TITLE
Tabcmd install failed : Could not find a version that satisfy the requirements

### ISSUE THREAD

**Issue by jambesh** [tableau/tabcmd#125]
I have installed Tabcmd using  : pip install git+https://github.com/tableau/tabcmd.git@development
it installed successfully but when i tried to invoke it from command like i am getting below error

The simple pip install tabcmd never worked for me - it complain with Error : Could not find a version that satisfy ...

I am using MAC OS, Apple Silicon Chip 

```
Failed to load language ' en ': [Errno 2] No translation file found for domain: 'tabcmd'
Traceback (most recent call last):
  File "/Users/xxx/opt/anaconda3/bin/tabcmd", line 5, in <module>
    from tabcmd.tabcmd import main
  File "/Users/xxx/opt/anaconda3/lib/python3.9/site-packages/tabcmd/tabcmd.py", line 3, in <module>
    from tabcmd.execution.tabcmd_controller import TabcmdController
  File "/Users/xxx/opt/anaconda3/lib/python3.9/site-packages/tabcmd/execution/tabcmd_controller.py", line 5, in <module>
    from .parent_parser import ParentParser
  File "/Users/xxx/opt/anaconda3/lib/python3.9/site-packages/tabcmd/execution/parent_parser.py", line 2, in <module>
    from . import _version
ImportError: cannot import name '_version' from 'tabcmd.execution' (/Usersxxx/opt/anaconda3/lib/python3.9/site-packages/tabcmd/execution/__init__.py)
```

**Comment by jacalata** [comment]
Thanks for the heads up! I had forgotten to actually publish to pypi 😞 
pip install should now work, and installing from the development branch should also work. Let me know if either of them doesn't work for you.

**Comment by jambesh** [comment]
Thanks Jac, I am able to install  now using  "pip install tabcmd"   but when i invoke it, it still complain with below error
i tried on apple mac os intel this time and all have the below error 
----------------------------------------------------------------------------------------------------------
Failed to load language ' en ': [Errno 2] No translation file found for domain: 'tabcmd'
Traceback (most recent call last):
  File "/Users/jambes/opt/anaconda3/bin/tabcmd", line 5, in <module>
    from src.tabcmd import main
  File "/Users/jambes/opt/anaconda3/lib/python3.9/site-packages/src/tabcmd.py", line 3, in <module>
    from src.execution.tabcmd_controller import TabcmdController
  File "/Users/jambes/opt/anaconda3/lib/python3.9/site-packages/src/execution/tabcmd_controller.py", line 5, in <module>
    from .parent_parser import ParentParser
  File "/Users/jambes/opt/anaconda3/lib/python3.9/site-packages/src/execution/parent_parser.py", line 2, in <module>
    from . import _version
ImportError: cannot import name '_version' from 'src.execution' (/Users/jambes/opt/anaconda3/lib/python3.9/site-packages/src/execution/__init__.py)

**Comment by jacalata** [comment]
Hi Jambesh - I forgot to update you but this is fixed now, and I've added smoke tests for future versions uploaded to pypi so I catch this!
