### ISSUE TITLE
login error: must not undeclare prefix ?

### ISSUE THREAD

**Issue by YEETTTTTTT** [tableau/tabcmd#156]
I'm trying to login but I get this error:

`INFO:  Creating new session
INFO:  must not undeclare prefix: line 2, column 0
Traceback (most recent call last):
  File "/Users/name/opt/anaconda3/lib/python3.9/xml/etree/ElementTree.py", line 1722, in feed
    self.parser.Parse(data, False)
xml.parsers.expat.ExpatError: must not undeclare prefix: line 2, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/src/execution/tabcmd_controller.py", line 43, in run
    namespace.func.run_command(namespace)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/src/commands/auth/login_command.py", line 25, in run_command
    session.create_session(args)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/src/commands/auth/session.py", line 237, in create_session
    self._create_new_connection()
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/src/commands/auth/session.py", line 141, in _create_new_connection
    self.tableau_server = self._set_connection_options()
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/src/commands/auth/session.py", line 135, in _set_connection_options
    tableau_server = TSC.Server(self.server_url, use_server_version=True, http_options=http_options)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/tableauserverclient/server/server.py", line 97, in __init__
    self.use_server_version()
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/tableauserverclient/server/server.py", line 139, in use_server_version
    self.version = self._determine_highest_version()
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/tableauserverclient/server/server.py", line 129, in _determine_highest_version
    version = self.server_info.get().rest_api_version
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 186, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/tableauserverclient/server/endpoint/server_info_endpoint.py", line 30, in get
    server_info = ServerInfoItem.from_response(server_response.content, self.parent_srv.namespace)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/tableauserverclient/models/server_info_item.py", line 35, in from_response
    parsed_response = fromstring(resp)
  File "/Users/name/opt/anaconda3/lib/python3.9/site-packages/defusedxml/common.py", line 126, in fromstring
    parser.feed(text)
  File "/Users/name/opt/anaconda3/lib/python3.9/xml/etree/ElementTree.py", line 1724, in feed
    self._raiseerror(v)
  File "/Users/name/opt/anaconda3/lib/python3.9/xml/etree/ElementTree.py", line 1631, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: must not undeclare prefix: line 2, column 0`

I do not really understand the error - how can I resolve it?

**Comment by jacalata** [comment]
Do you know what version of Tableau Server you are running against?

**Comment by jacalata** [comment]
If you're still seeing this, try visiting your-server-name/api/3.16/serverInfo in a browser, and share what you see on that page.

**Comment by jacalata** [comment]
I'm going to close this as I can't reproduce it, and haven't heard back. Hopefully it was fixed by improvements since then.
