### ISSUE TITLE
Windows installer: Error: ENOENT: no such file or directory, stat './dist/windows/tabcmd/tabcmd.exe'

### ISSUE THREAD

**Issue by jacalata** [tableau/tabcmd#178]

**Comment by jacalata** [comment]
Because it got named tabcmd-windows.exe 

BUT when that is run: it hasn't bundled tsc?
c:\dev\tabcmd2\dist\windows>tabcmd-windows.exe
Traceback (most recent call last):
  File "C:\dev\tabcmd2\tabcmd\tabcmd.py", line 3, in <module>
    from tabcmd.execution.tabcmd_controller import TabcmdController
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tabcmd\execution\tabcmd_controller.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tabcmd\execution\map_of_commands.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tabcmd\commands\auth\login_command.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tabcmd\commands\server.py", line 4, in <module>
ModuleNotFoundError: No module named 'tableauserverclient'
[41724] Failed to execute script 'tabcmd' due to unhandled exception!
