### ISSUE TITLE
when logging in getting xml.parsers.expat.ExpatError: must not undeclare prefix: line 2, column 0

### ISSUE THREAD

**Issue by ejoynes** [tableau/tabcmd#204]
I think this is the same issue as closed issue https://github.com/tableau/tabcmd/issues/156

INFO:  Creating new session
INFO:  must not undeclare prefix: line 2, column 0
Traceback (most recent call last):
  File "C:\Users\f404632\.conda\envs\sp\lib\xml\etree\ElementTree.py", line 1722, in feed
    self.parser.Parse(data, False)
xml.parsers.expat.ExpatError: must not undeclare prefix: line 2, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\src\execution\tabcmd_controller.py", line 43, in run
    namespace.func.run_command(namespace)
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\src\commands\auth\login_command.py", line 25, in run_command
    session.create_session(args)
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\src\commands\auth\session.py", line 237, in create_session
    self._create_new_connection()
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\src\commands\auth\session.py", line 141, in _create_new_connection
    self.tableau_server = self._set_connection_options()
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\src\commands\auth\session.py", line 135, in _set_connection_options
    tableau_server = TSC.Server(self.server_url, use_server_version=True, http_options=http_options)
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\tableauserverclient\server\server.py", line 97, in __init__
    self.use_server_version()
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\tableauserverclient\server\server.py", line 139, in use_server_version
    self.version = self._determine_highest_version()
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\tableauserverclient\server\server.py", line 129, in _determine_highest_version
    version = self.server_info.get().rest_api_version
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 186, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\tableauserverclient\server\endpoint\server_info_endpoint.py", line 30, in get
    server_info = ServerInfoItem.from_response(server_response.content, self.parent_srv.namespace)
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\tableauserverclient\models\server_info_item.py", line 35, in from_response
    parsed_response = fromstring(resp)
  File "C:\Users\f404632\.conda\envs\sp\lib\site-packages\defusedxml\common.py", line 126, in fromstring
    parser.feed(text)
  File "C:\Users\f404632\.conda\envs\sp\lib\xml\etree\ElementTree.py", line 1724, in feed
    self._raiseerror(v)
  File "C:\Users\f404632\.conda\envs\sp\lib\xml\etree\ElementTree.py", line 1631, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: must not undeclare prefix: line 2, column 0

**Comment by ejoynes** [comment]
Tableau Server Version: 2021.4.3 (20214.22.0108.1039) 64-bit Windows
tableauserverclient==0.19
tabcmd==2.0.5

**Comment by jacalata** [comment]
Could you try downloading the newest version of tabcmd? It should be 2.0.7.

**Comment by jacalata** [comment]
I think this error means you are getting a non-xml response, which usually points to a problem in your request. Can you share the command line you used? (make sure to remove any passwords or information that shouldn't be public).

**Comment by jacalata** [comment]
I've identified this in the underlying tsc library, and it will be fixed in the next release of that.

**Comment by jacalata** [comment]
This is fixed in the february release, 2.0.11
